name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: build i386 toolchain
      shell: bash
      run: |
        make crossgcc-i386 CPUS=$(nproc)
    - name: build Aarch64 toolchain
      shell: bash
      run: |
        make crossgcc-aarch64 CPUS=$(nproc)
    - name: build RISC-V toolchain
      shell: bash
      run: |
        make crossgcc-riscv CPUS=$(nproc)
    - name: build the payload
      shell: bash
      run: |
        make -C payloads/coreinfoolddefconfig
        make -C payloads/coreinfo
    - name: configure the build
      shell: bash
      run: |
        make menuconfig
